kind: pipeline
type: docker
name: default

steps:
- name: Build & publish  
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password: 
      from_secret: docker_password
    repo: handspiker2/handbrake-transcode-job
    tags: 
      - latest
      - '1.8'
      - '1.8.1'
    dry_run: false
  when:
    branch:
    - main

- name: Build & publish (Test build)
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password: 
      from_secret: docker_password
    repo: handspiker2/handbrake-transcode-job
    tags: test-build
    dry_run: false
  when:
    event:
    - promote
    target:
    - test-build

# Just test build branches
- name: Build  
  image: plugins/docker
  settings:
    repo: handspiker2/handbrake-transcode-job
    tags: latest
    dry_run: true
  when:
    branch:
      exclude:
      - main
      - test-build
    event:
    - push