variables:
  - &handbrake_version 1.10.0

steps:
# Just test build branches
- name: Build
  image: woodpeckerci/plugin-docker-buildx
  settings:
    repo: handspiker2/handbrake-transcode-job
    tags:
      - latest
      - *handbrake_version
    build_args: "HANDBRAKE_GIT_TAG=1.10.0"
    auto_labels: false
    platforms: linux/amd64
    dry_run: true
  when:
    branch:
      exclude:
      - main
    event: push

- name: Build & publish
  image: woodpeckerci/plugin-docker-buildx
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: handspiker2/handbrake-transcode-job
    tags:
      - latest
      - *handbrake_version
    build_args: "HANDBRAKE_GIT_TAG=1.10.0"
    dry_run: false
    platforms: linux/amd64
  when:
    branch:
    - main
    event: [push, manual]
