steps:
# Just test build branches
- name: Build  
  image: woodpeckerci/plugin-docker-buildx
  settings:
    repo: handspiker2/handbrake-transcode-job
    tags: latest
    auto_labels: false
    platforms: linux/amd64,linux/arm64/v8
    dry_run: true
  when:
    branch:
      exclude:
      - main
  backend_options:
      kubernetes:
        resources:
          requests:
            memory: 512Mi
            cpu: 1500m
          limits:
            memory: 2Gi
            cpu: 1500m