matrix:
  platform:
    - amd64
    - arm64


labels:
  platform: linux/${platform}

steps:
# Just test build branches
- name: Build  
  image: woodpeckerci/plugin-docker-buildx
  settings:
    repo: handspiker2/handbrake-transcode-job
    tags: latest
    auto_labels: false
    platforms: linux/${platform}
    dry_run: true
  when:
    branch:
      exclude:
      - main